<?php

namespace Hyperion\PersonalBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PortfolioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PortfolioRepository extends EntityRepository
{
}
