<?php

namespace Hyperion\PersonalBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\Expr\Join;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{
    
    public function findAllBlogPosts() {
        $query = $this->createQueryBuilder('p')
                ->leftJoin('HyperionPersonalBundle:Portfolio', 'po', Join::WITH, 'po.post = p.id')
                ->where('po IS NULL');
         
        return $query->getQuery()->getResult();
    }
            
}
